downstream_package_name: rpmdeplint
jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-29-x86_64
    - fedora-30-x86_64
    - fedora-31-x86_64
    - fedora-rawhide-x86_64
  trigger: pull_request
specfile_path: rpmdeplint.spec
synced_files:
- rpmdeplint.spec
- .packit.yaml
upstream_package_name: rpmdeplint
